### ISSUE TITLE
Can't get barcode scanner to work

### ISSUE THREAD

**Issue by ramdroid** [Coppernic/BarcodeSample#1]
I got a C-One device (Android 7.1.2, build 20190219) and from F-Droid installed the following apps:

- Core Service C-One2 (1.8.18)
- Barcode Manager (1.3.0)
- Barcode Sample (1.0.3)

I have no idea how to setup the barcode reader. According to the spec it's supposed to be a N6603 device but port and baud rate are not specified.

With default setting the sample app says "EXPOSURE_MODE LIGHT_MODE SCAN_TIMEOUT".
When setting N6603 and empty settings for port/baudrate "SCAN TIMEOUT"

When enabling "Use Connector" the app just crashes:

> 01-07 16:04:24.571 22643 22643 D BarcodeFragment: onStart
01-07 16:04:24.612  2035  3731 W ActivityManager: Unable to start service Intent { act=fr.coppernic.intent.action.stop.barcode.service pkg=fr.coppernic.service.conen cmp=fr.coppernic.service.conen/fr.coppernic.service.barcode.CpcBarcodeService } U=0: not found
01-07 16:04:24.614 22643 22643 D BarcodeFragment: onCreated fr.coppernic.sdk.barcode.service.BarcodeReaderConnector@f0647b9
01-07 16:04:24.692 22643 22659 D OpenGLRenderer: endAllActiveAnimators on 0x7f7b0f1000 (RippleDrawable) with handle 0x7f7a557140
01-07 16:04:25.490 21928 21928 I ServiceManager: Waiting for service AtCmdFwd...
01-07 16:04:25.898 22643 22643 D BarcodeReaderConnector: Binding to service
01-07 16:04:25.898   609   609 I AudioPolicyManagerCustom: FLAG None hence request for a primary output
01-07 16:04:25.902   609  1029 I AudioPolicyManagerCustom: FLAG None hence request for a primary output
01-07 16:04:25.903   609   965 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
01-07 16:04:25.904   609   965 D audio_hw_extn: audio_extn_set_anc_parameters: anc_enabled:0
01-07 16:04:25.950  2035  3693 W ActivityManager: Unable to start service Intent { act=fr.coppernic.service.barcode.BIND pkg=fr.coppernic.service.conen } U=0: not found
01-07 16:04:25.950 22643 22643 E BarcodeReaderConnector: Cannot bind to service
01-07 16:04:25.958 22643 22643 D AndroidRuntime: Shutting down VM
01-07 16:04:25.959 22643 22643 E AndroidRuntime: FATAL EXCEPTION: main
01-07 16:04:25.959 22643 22643 E AndroidRuntime: Process: fr.coppernic.sample.barcode, PID: 22643
01-07 16:04:25.959 22643 22643 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List fr.coppernic.sdk.barcode.IBarcodeReader.getSupportedParameters()' on a null object reference
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at fr.coppernic.sdk.barcode.service.BarcodeReaderConnector.getSupportedParameters(BarcodeReaderConnector.java:314)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at fr.coppernic.sample.barcode.BarcodeFragment.updateSpinnerParam(BarcodeFragment.java:527)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at fr.coppernic.sample.barcode.BarcodeFragment.access$500(BarcodeFragment.java:69)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at fr.coppernic.sample.barcode.BarcodeFragment$1.onOpened(BarcodeFragment.java:154)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at fr.coppernic.sdk.barcode.service.BarcodeReaderConnector.open(BarcodeReaderConnector.java:194)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at fr.coppernic.sample.barcode.BarcodeFragment.open(BarcodeFragment.java:464)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at fr.coppernic.sample.barcode.BarcodeFragment.onOpen(BarcodeFragment.java:331)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at fr.coppernic.sample.barcode.BarcodeFragment_ViewBinding$1.doClick(BarcodeFragment_ViewBinding.java:51)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at android.view.View.performClick(View.java:5637)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:22433)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6121)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-07 16:04:25.959 22643 22643 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
01-07 16:04:25.965  2035 11475 W ActivityManager:   Force finishing activity fr.coppernic.sample.barcode/.BarcodeActivity
01-07 16:04:25.970  2035 11475 D ActivityTrigger: ActivityTrigger activityPauseTrigger
01-07 16:04:25.970  2035 11475 W ActivityManager:   Force finishing activity fr.coppernic.sample.barcode/.BarcodeActivity

**Comment by ramdroid** [comment]
Issue has been resolved by support.
